version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=<database>
      - POSTGRES_USER=<user>
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
  
volumes:
  db_data: {}