version: '3.9'

services:
  workspace:
    container_name: ${PROJECT_NAME:-default}-workspace
    image: mcr.microsoft.com/devcontainers/java:17-bullseye
    tty: true
    volumes:
      - ../project/:/home/vscode/workspace:cached
    ports:
      - 5555:5555
