version: '3'

services:
  db:
    image: mysql:8.0.19
    environment:
      - MYSQL_DATABASE=<databaseName>
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - <backend>-mariadb

volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  <backend>-mariadb: {}