version: '3.7'

services:
  nestjs:
    build: 
      context: .
      target: developmen
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000