version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - BACKEND_ADDR=backend:<port>
      - FRONTEND_ADDR=frontend:<port>
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    # depends_on:
      # - backend
      # - frontend